# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c09bb85e6958ca7daac0de2a6b7f1a82c68b39533f6e8f9c83af4d6e156ace2e2373cc1fcd747713887d17907098bba417842c887121fbe31a1c6917a72d1b2

test:
  secret_key_base: 5f1f90f3a7c311a32ae0fdf25bfbfb76d4ffe957f15227e0001cf512e2860006bc559542775642129af68fd6fe1d339b10f9f70980c5de829a5e5c4cd48aadc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
